### ISSUE TITLE
Vim crashes with empty string argument

### ISSUE THREAD

**Issue by rhysd** [rhysd/vim.wasm#34]
### Describe the bug

When passing an empty string as command line argument of Vim, Vim crashes on start.

### Steps To Reproduce

```js
import { VimWasm } from '/path/to/vim-wasm/vimwasm.js';

const vim = new VimWasm({ ... });

vim.start({ debug: true, cmdArgs: [ '' ] });
```

Run above script in browser and check console in DevTools.

Or access to http://rhysd.github.io/vim.wasm/?arg=

### Expected behavior

Vim normally starts with an unnamed buffer

### Actual behavior

Vim crashes with following abort error:

```
worker: Error was thrown in worker: abort("TypeError: Cannot read property 'mode' of null") at Error
    at jsStackTrace (http://localhost:1234/vim.js:1374:13)
    at stackTrace (http://localhost:1234/vim.js:1391:12)
    at abort (http://localhost:1234/vim.js:8200:44)
    at ___syscall33 (http://localhost:1234/vim.js:5581:69)
    at _access (wasm-function[4982]:59)
    at _readfile (wasm-function[1636]:2316)
    at _open_buffer (wasm-function[175]:1086)
    at _create_windows (wasm-function[4640]:792)
    at _vim_main2 (wasm-function[4638]:1543)
    at _wasm_main (wasm-function[4629]:1356)
```

### Screenshots/DevTools console (if possible)

![スクリーンショット 2019-08-01 15 50 30](https://user-images.githubusercontent.com/823277/62271832-8f9abe80-b474-11e9-8f3d-c7741c589f29.png)

### Your environment

 - OS: macOS 10.12
 - Browser: Chrome
 - Browser Version: 75.0.3770.100

**Comment by rhysd** [comment]
This seems a bug of implementation of `access()` in emscripten. I created https://github.com/emscripten-core/emscripten/issues/9136

**Comment by rhysd** [comment]
Fix was merged and the issue was fixed in upstream. With next release, this issue should be fixed.

**Comment by rhysd** [comment]
emscripten 1.38.41 fixed this issue. I confirmed it with v0.0.12.
